################################# Default configuration ###################
baseURL = "http://riedltransportgmbh.github.io/"
title = "Elmar Riedl Transport GmbH"
theme = "MVSailauf"
# disable language
defaultContentLanguage = "de"
timeout = "10m"
disableKinds = ['rss']


################### German Navigation ########################
[[menu.main]]
name = "Aktuelles"
url = "/aktuelles"
weight = 1

[[menu.main]]
name = "Kontakt"
url = "/kontakt"
weight = 7


[[menu.main]]
name = "Impressum"
url = "/imprint"
weight = 11 



############################# Default Parameters ##########################
[params]
logo = "images/logo_riedl.jpg"
jugendlogo = "images/logo_riedl.jpg"
maskottchen = "images/Engelbert.svg"
author = "Linda Schneider und Julian Thomas"
title = "Elmar Riedl Transport GmbH"
ustid = ""

################################ German Language ########################
[languages.de]
languageName = "De"
languageCode = "de-de"
contentDir = "content/german"
weight = 2
copyright = "Copyright &copy; 2025 Riedl Transport GmbH"
